// Envelope encryption for stored secrets (provider API keys, OAuth refresh
// tokens). Each secret gets its own data encryption key (DEK) generated by
// AWS KMS. We store the KMS-wrapped DEK alongside AES-256-GCM ciphertext.
//
// Why envelope: KMS Encrypt has a 4 KB plaintext cap and per-call cost.
// Generating a DEK once per secret means we only call KMS for the wrap,
// while the bulk encryption stays local.
//
// Key context binds ciphertext to a user_id + purpose so a row swap would
// fail decryption — KMS enforces it on the unwrap call.

import {
  KMSClient,
  GenerateDataKeyCommand,
  DecryptCommand,
} from '@aws-sdk/client-kms'
import { createCipheriv, createDecipheriv, randomBytes } from 'node:crypto'

let _client: KMSClient | null = null

function client(): KMSClient {
  if (!_client) {
    _client = new KMSClient({ region: process.env.AWS_REGION ?? 'us-east-1' })
  }
  return _client
}

function keyId(): string {
  const id = process.env.AWS_KMS_KEY_ID
  if (!id) throw new Error('AWS_KMS_KEY_ID is not set')
  return id
}

export interface EncryptionContext {
  userId: string
  purpose: 'provider_secret' | 'oauth_refresh'
  // Stable per-row identifier so the DEK can never be moved between rows.
  rowId: string
}

export interface SealedSecret {
  dekCiphertext: string   // base64 — KMS-wrapped DEK
  ciphertext: string      // base64
  iv: string              // base64 (12 bytes for GCM)
  tag: string             // base64 (16 bytes)
}

function ctxToKms(ctx: EncryptionContext): Record<string, string> {
  return {
    userId: ctx.userId,
    purpose: ctx.purpose,
    rowId: ctx.rowId,
  }
}

export async function seal(
  plaintext: string,
  ctx: EncryptionContext,
): Promise<SealedSecret> {
  const dek = await client().send(
    new GenerateDataKeyCommand({
      KeyId: keyId(),
      KeySpec: 'AES_256',
      EncryptionContext: ctxToKms(ctx),
    }),
  )
  if (!dek.Plaintext || !dek.CiphertextBlob) {
    throw new Error('KMS GenerateDataKey returned empty material')
  }
  const iv = randomBytes(12)
  const cipher = createCipheriv('aes-256-gcm', Buffer.from(dek.Plaintext), iv)
  const ct = Buffer.concat([cipher.update(plaintext, 'utf8'), cipher.final()])
  const tag = cipher.getAuthTag()
  // Don't keep the plaintext DEK in memory longer than needed.
  ;(dek.Plaintext as Uint8Array).fill(0)

  return {
    dekCiphertext: Buffer.from(dek.CiphertextBlob).toString('base64'),
    ciphertext: ct.toString('base64'),
    iv: iv.toString('base64'),
    tag: tag.toString('base64'),
  }
}

export async function open(
  sealed: SealedSecret,
  ctx: EncryptionContext,
): Promise<string> {
  const unwrapped = await client().send(
    new DecryptCommand({
      CiphertextBlob: Buffer.from(sealed.dekCiphertext, 'base64'),
      EncryptionContext: ctxToKms(ctx),
    }),
  )
  if (!unwrapped.Plaintext) {
    throw new Error('KMS Decrypt returned no plaintext')
  }
  const decipher = createDecipheriv(
    'aes-256-gcm',
    Buffer.from(unwrapped.Plaintext),
    Buffer.from(sealed.iv, 'base64'),
  )
  decipher.setAuthTag(Buffer.from(sealed.tag, 'base64'))
  const pt = Buffer.concat([
    decipher.update(Buffer.from(sealed.ciphertext, 'base64')),
    decipher.final(),
  ])
  ;(unwrapped.Plaintext as Uint8Array).fill(0)
  return pt.toString('utf8')
}
